# Site settings
title: Ireland
client:
  name: Tourism Ireland
  link: https://www.ireland.com/en-gb
core-se-link: https://www.secretescapes.com/current-sales
description: >
  From County Donegal’s sublime coast to Derry~Londonderry’s cultural buzz, Ireland’s North-West makes for a wild getaway. Marry your city break to an outdoor escape for the perfect adventure into Ireland’s undiscovered North-West. Discover the variety of experiences you can add to your itinerary here.  

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/ireland" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/ireland/_assets/img"
css:     "/uk/2020/ireland/_assets/css"
js:      "/uk/2020/ireland/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed