# Site settings
title: Ireland
client:
  name: Tourism Ireland
  link: https://www.ireland.com/en-gb
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/ireland" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/ireland/_assets/img"
css:     "/uk/2020/ireland/_assets/css"
js:      "/uk/2020/ireland/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed